### ISSUE TITLE
TypeError: Cannot read property 'detection' of undefined

### ISSUE THREAD

**Issue by timdonovanuk** [thebigpotatoe/face-recognition-docker#4]
Sorry, I know you're busy - maybe someone else using this can eventually debug it at some point!

Troubleshooting this error is way beyond my abilities: 

```
#13 67.85 Processing faces in Tim
#13 67.85 - Started processing 20161022_112243_0F533AAB.jpg
#13 67.90 - Started processing 20161219_231659_C7700EE7.jpg
#13 67.91 - Started processing 20170816_144308_3F203C38.jpg
#13 113.7 - Finsihed processing file 20161219_231659_C7700EE7.jpg (1 out of 3)
#13 115.6 - Finsihed processing file 20170816_144308_3F203C38.jpg (2 out of 3)
#13 115.6 /usr/app/node_modules/face-api.js/build/commonjs/factories/WithFaceDetection.js:5
#13 115.6     return obj['detection'] instanceof FaceDetection_1.FaceDetection;
#13 115.6               ^
#13 115.6
#13 115.6 TypeError: Cannot read property 'detection' of undefined
#13 115.6     at Object.isWithFaceDetection (/usr/app/node_modules/face-api.js/build/commonjs/factories/WithFaceDetection.js:5:15)
#13 115.6     at /usr/app/node_modules/face-api.js/build/commonjs/draw/drawDetections.js:11:36
#13 115.6     at Array.forEach (<anonymous>)
#13 115.6     at Object.drawDetections (/usr/app/node_modules/face-api.js/build/commonjs/draw/drawDetections.js:8:21)
#13 115.6     at /usr/app/descriptor-creator.js:85:34
#13 115.6     at processTicksAndRejections (node:internal/process/task_queues:94:5)
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c node descriptor-creator.js]: exit code: 1
```

if I run over the Penny/Sheldon folders I don't get an error - but as soon as I add my own folder to /faces with photos in, it throws this error. 

Is there something wrong with my face? ;D

**Comment by timdonovanuk** [comment]
Ah I think it is an issue when no face is detected in a photo. I've cropped some of them down and it's working now. Thanks!

**Comment by thebigpotatoe** [comment]
Ah awesome, that is a bug clearly. Although when trying to run descriptors you should only have one face and that should be of the person you want to create a descriptor for.
